In [1]:
import pandas as pd
import os
from os import listdir
from datetime import datetime, timedelta

import numpy as np


# 그래프
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
path = 'C:/windows/Fonts/malgun.ttf'                           # 폰트:맑은고딕
font_name = fm.FontProperties(fname=path, size=24).get_name()  
plt.rc('font', family=font_name)

In [2]:
##########
# 자료 불러오기
#####

# 경로 설정
directory_name = "./data_naver"

# 파일명 가져오기
file_names = listdir(directory_name)
# file_names = file_names[1:]

# file_names = file_names[1:]

In [9]:
file_names[0][-15:-5]

'2022-07-01'

In [10]:
data = pd.DataFrame()

# 전체 자료 불러오기 & 병합
for open_file in file_names:
    df_temp = pd.read_excel(directory_name +'/'+ open_file, 0)
    df_temp['DATE'] = open_file[-15:-5]
    data = pd.concat([data, df_temp], ignore_index=True)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:214: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [12]:
data.tail(2)

,상품카테고리(대),상품카테고리(중),상품카테고리(소),상품카테고리(세),상품명,상품ID,성별,나이,결제금액,결제수,결제상품수량,환불금액,환불건수,환불수량,DATE
99177,출산/육아,아기간식,유아유제품,-,상하목장 마이리틀 딸기&블루베리 85g x 12팩_냉장,4939051927,여성,31~35,0.0,0.0,0.0,18810.0,2.0,2.0,2022-09-02
99178,출산/육아,아기간식,유아유제품,-,상하목장 마이리틀 사과&바나나 85g x 12팩_냉장,4939057102,여성,31~35,0.0,0.0,0.0,9900.0,1.0,1.0,2022-09-02

In [4]:
# pd.read_excel(directory_name +'/'+ open_file, 0)

In [18]:
data['DATE'] = pd.to_datetime(data['DATE'],  format = '%Y-%m-%d')

In [14]:
s_dt1= (datetime.today()- timedelta(0)).strftime('%Y%m%d')
excel_name = s_dt1+ '_상품_인구통계_v1.xlsx'
writer = pd.ExcelWriter(excel_name)

data.to_excel(writer, 'Sheet1')

writer.save()
writer.close()

In [5]:
data = pd.read_excel('./20220922_상품_인구통계_v1.xlsx', 0)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99179 entries, 0 to 99178
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  99179 non-null  int64
 1   상품카테고리(대)   99179 non-null  object
 2   상품카테고리(중)   99179 non-null  object
 3   상품카테고리(소)   99179 non-null  object
 4   상품카테고리(세)   99179 non-null  object
 5   상품명         99179 non-null  object
 6   상품ID        99179 non-null  int64
 7   성별          99179 non-null  object
 8   나이          99179 non-null  object
 9   결제금액        99179 non-null  int64
 10  결제수         99179 non-null  int64
 11  결제상품수량      99179 non-null  int64
 12  환불금액        99179 non-null  int64
 13  환불건수        99179 non-null  int64
 14  환불수량        99179 non-null  int64
 15  DATE        99179 non-null  object
dtypes: int64(8), object(8)
memory usage: 12.1+ MB

In [17]:
data[(data['상품명'].str.contains('아이스크림')) ].상품명.unique()

array(['[리뷰 3,000원][2+1][상하목장] 유기농아이스크림 밀크 474mX2개+ 딸기 474mL 1개',
       '[매일유업] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[리뷰2,000원][매일유업] 상하목장 유기농아이스크림 밀크 100mL 4개',
       '[홀더1개증정][매일유업] 상하목장 얼려먹는 아이스크림 밀크 85ml 24개입',
       '[홀더1개증정][매일유업] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[리뷰 1,000원][매일유업] 상하목장 유기농 아이스크림 474ml (밀크1개+딸기1개) 총 2입',
       '[리뷰 2,000원][상하목장] 유기농 아이스크림 100mL 4입(딸기 2개+밀크 2개)',
       '[리뷰 3,000원][2+1][상하목장] 유기농아이스크림 딸기 474mLX2개+ 밀크 474mL 1개',
       '[매일유업] 마이카페라떼 아이스크림mix라떼 220ml 10팩_냉장',
       '[리뷰 1,000원][매일유업] 상하목장 유기농 아이스크림 밀크 474mL 1개',
       '[리뷰 2,000원][매일유업] 상하목장 유기농아이스크림 딸기 100mL 4개',
       '[리뷰 1,000원][매일유업] 상하목장 유기농아이스크림 딸기 474mL 1개',
       '[매일유업] 상하목장 얼려먹는 아이스크림 밀크 85ml 24개입',
       '[상하목장 아이스크림 증정][매일유업] 상하키친 칠리치즈포테이토브리또 130g 4개+로제치킨브리또 130g 4개+불고기마요브리또 130g 4개 (총 12개)_냉동',
       '[매일유업] 소잘우유케이크 360g 1개+ 상하목장 미니아이스크림 100ml 밀크1개, 딸기1개_냉동',
       '[상하목장 아이스크림 100ml x 2개증정][매일유업] 상하키친 칠리치즈포테이토브리또 130g 4개+로제치킨브리또 130g 4개+불고기마요브리또 130g 4개 (총 12개)_냉동',
       '[리뷰3,000원][2+1][상하목장] 유기농아이스크림 밀크 474ml 2개+ 딸기 474mL 1개',
       '[리뷰 1,000원][상하목장] 유기농 아이스크림 100mL 4입(딸기 2개+밀크 2개)',
       '[깜짝딜] 상하목장 유기농 아이스크림 밀크 100ml 4개 + 딸기 100ml 4개 (총8개)',
       '[리뷰 1,000원][매일유업] 상하목장 유기농아이스크림 딸기 100mL 4개',
       '[리뷰1,000원][매일유업] 상하목장 유기농아이스크림 밀크 100mL 4개',
       '[리뷰 1,500원][매일유업] 상하목장 유기농아이스크림 딸기 474mL 1개',
       '[리뷰1,000원][매일유업]폴바셋 밀크 아이스크림 멀티팩 100ml 4개입',
       '[리뷰1,000원][매일유업]폴바셋 커피 아이스크림 멀티팩 100ml 4개입',
       '[매일유업] 상하목장 유기농 아이스크림 474ml (밀크1개+딸기1개) 총 2입',
       '[깜짝딜][매일유업] 마이카페라떼 아이스크림mix라떼 220ml 10팩_냉장',
       '[상하목장] 유기농 아이스크림 100mL 4입(딸기 2개+밀크 2개)',
       '[홀더 증정][매일유업] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[2+1] 폴바셋 모나카 아이스크림(3개입) x 2박스+1박스 증정 (총3박스)',
       '[매일유업]폴바셋 아이스크림 멀티팩 100ml 4개입 (밀크/커피 택1)',
       '[매일유업]폴 바셋 아이스크림 멀티팩 100ml 4개입 (밀크/커피 택1)',
       '[2+1] 폴 바셋 모나카 아이스크림(3개입) x 2박스+1박스 증정 (총3박스)',
       '[홀더증정][매일유업] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[홀더증정][매일유업] 상하목장 얼려먹는 아이스크림 밀크 85ml 24개입',
       '[포토리뷰1,000원][매일유업] 마이카페라떼 아이스크림mix라떼 220ml 10팩_냉장',
       '[히든딜] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[히든딜] [미니컵 100ml 딸기1개, 밀크1개 증정]상하목장 유기농 아이스크림 파인트 474ml (밀크2개+딸기1개)_(총5개)',
       '[깜짝딜] 마이카페라떼 아이스크림mix라떼 220ml 10팩_냉장',
       '[홀더1개 증정] 상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '[2+1][상하목장] 유기농아이스크림 밀크 474ml 2개+ 딸기 474mL 1개',
       '[홀더1개 증정] 상하목장 얼려먹는 아이스크림 밀크 85ml 24개입',
       '[2+1][상하목장] 유기농아이스크림 딸기 474mLX2개+ 밀크 474mL 1개',
       '[매일유업] 상하목장 유기농아이스크림 밀크 100mL 4개',
       '[깜짝딜] 상하목장 유기농 아이스크림 밀크 100ml 4개 + 딸기 100ml 4개 (총8개)(ID당 최대1개 구매가능)',
       '[고리수건2개증정][매일유업]얼려먹는 아이스크림 초코 85mL 24팩 + 얼려먹는 아이스주스 밀크 85ml 24팩 (총2box)',
       '[매일유업] 상하목장 유기농아이스크림 딸기 100mL 4개',
       '마이카페라떼 아이스크림mix라떼 220ml 10팩_냉장',
       '[리뷰1,000원] 상하목장 유기농 아이스크림 밀크 474mL 1개',
       '상하목장 유기농아이스크림 딸기 100mL 4개', '상하목장 얼려먹는 아이스크림 초코 85ml 24개입',
       '상하목장 유기농 아이스크림 474ml 밀크1개+딸기1개 (총 2개)',
       '[2+1] 상하목장 유기농아이스크림 딸기 474mL 2개 + 밀크 474mL 1개 (총 3개)',
       '상하목장 얼려먹는 아이스크림 밀크 85ml 24개입',
       '상하목장 유기농 아이스크림 100mL 딸기 + 밀크 각 2개 (총 4개)',
       '[리뷰1,000원] 상하목장 유기농아이스크림 딸기 474mL 1개',
       '상하목장 유기농 아이스크림 밀크 100ml 4개 + 딸기 100ml 4개 (총8개)',
       '상하목장 유기농아이스크림 밀크 100mL 4개'], dtype=object)

In [13]:
data[(data['상품명'].str.contains('아이스크림')) & (data['상품명'].str.contains('474'))].groupby('나이')['상품명'].count()

나이
(알수없음)      4
14~16       2
17~19      16
20~25     128
26~30     269
31~35     303
36~40     331
41~45     317
46~50     243
51~55     106
56~60      57
61~65      38
66~70      24
71+         7
Name: 상품명, dtype: int64

In [18]:
data[(data['상품명'].str.contains('아이스크림')) & (data['상품명'].str.contains('100'))].groupby('나이')['상품명'].count()

나이
17~19      4
20~25     37
26~30    130
31~35    166
36~40    187
41~45    171
46~50    109
51~55     40
56~60     15
61~65     15
66~70      7
71+        3
Name: 상품명, dtype: int64

In [25]:
pd.pivot_table(data, values='결제금액', index=['나이'],columns=['DATE'],  aggfunc='sum')

DATE,2022-07-01,2022-07-02,2022-07-03,2022-07-04,2022-07-05,2022-07-06,2022-07-07,2022-07-08,2022-07-09,2022-07-10,...,2022-08-24,2022-08-25,2022-08-26,2022-08-27,2022-08-28,2022-08-29,2022-08-30,2022-08-31,2022-09-01,2022-09-02
나이,,,,,,,,,,,,,,,,,,,,,
(알수없음),140530.0,11610.0,12900.0,161620.0,93210.0,99960.0,294760.0,151300.0,15750.0,182520.0,...,156400.0,216620.0,713570.0,43900.0,59310.0,79060.0,100000.0,127920.0,332010.0,130030.0
11~13,8010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14~16,27900.0,68500.0,143380.0,8910.0,NaN,NaN,15900.0,NaN,36900.0,119070.0,...,44700.0,17900.0,33070.0,18780.0,118180.0,0.0,125520.0,17900.0,56980.0,42800.0
17~19,188940.0,133710.0,125910.0,285480.0,254120.0,197120.0,193770.0,157570.0,121310.0,140390.0,...,204970.0,531270.0,525950.0,459410.0,259370.0,433260.0,379440.0,537360.0,396440.0,246290.0
20~25,3228320.0,1937460.0,3640220.0,4307350.0,3920790.0,4322420.0,3729530.0,3351850.0,1941020.0,2571860.0,...,4047460.0,4434260.0,4028440.0,3025630.0,4298740.0,8694420.0,5392520.0,5079530.0,6389910.0,3706980.0
26~30,12253360.0,7750730.0,11227830.0,16212250.0,13856460.0,12986470.0,12358340.0,9808560.0,7030410.0,10609980.0,...,12897750.0,13328100.0,10036620.0,7280060.0,10776420.0,26914170.0,15361200.0,12486280.0,23599560.0,10621650.0
31~35,25569920.0,14318040.0,22826290.0,32072950.0,25781980.0,30423450.0,23212510.0,21356270.0,14002850.0,21417730.0,...,25763190.0,27742260.0,20199960.0,13664270.0,21738160.0,70945190.0,27348410.0,25453470.0,51367320.0,26963310.0
36~40,23488950.0,15174300.0,20722660.0,33293850.0,29939810.0,37120010.0,27206100.0,20651780.0,16317570.0,22210520.0,...,25226760.0,27746170.0,23529520.0,14474370.0,20112960.0,81678060.0,29458930.0,27036300.0,50302760.0,25042360.0
41~45,15164040.0,12048100.0,15972050.0,21730730.0,19050570.0,25744500.0,18574290.0,17311830.0,12077170.0,14623140.0,...,20937340.0,18956200.0,17890610.0,15369980.0,15394310.0,54013330.0,21912920.0,18266280.0,28150000.0,16847690.0
46~50,9972480.0,6636700.0,9351440.0,12600950.0,8953430.0,14776290.0,9261380.0,8876010.0,5654670.0,7874340.0,...,10559650.0,10728990.0,9638000.0,6190140.0,9434790.0,23560130.0,10596520.0,10081770.0,12988330.0,8121690.0
51~55,4374840.0,3270730.0,3979230.0,5511480.0,5741500.0,6303020.0,5277020.0,3940680.0,2967820.0,4578660.0,...,5718730.0,4464590.0,5445700.0,4413460.0,4514130.0,10982930.0,6070910.0,5557400.0,6230910.0,4929810.0
56~60,2032540.0,1816880.0,1859720.0,2492150.0,2333290.0,2302570.0,1924380.0,1849980.0,1132430.0,1589320.0,...,1834200.0,2839710.0,1900490.0,1421410.0,1896460.0,3618420.0,2701770.0,1939710.0,3256040.0,1725080.0
61~65,1395960.0,828600.0,1175230.0,1453720.0,1424030.0,1240580.0,1026410.0,1182640.0,435880.0,822260.0,...,1289790.0,1350740.0,1116970.0,607370.0,1039600.0,2517970.0,1669160.0,1522600.0,1408970.0,1186790.0
66~70,586710.0,433160.0,424600.0,424250.0,267160.0,1112800.0,244800.0,494170.0,483810.0,369720.0,...,422350.0,389730.0,429250.0,473880.0,303450.0,861470.0,479050.0,634030.0,625050.0,386960.0
71+,360120.0,214730.0,400080.0,267920.0,101510.0,414970.0,609610.0,218600.0,131300.0,301630.0,...,156060.0,523190.0,195430.0,74500.0,217570.0,415740.0,240800.0,420470.0,295630.0,244940.0
8~10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
data

,상품카테고리(대),상품카테고리(중),상품카테고리(소),상품카테고리(세),상품명,상품ID,성별,나이,결제금액,결제수,결제상품수량,환불금액,환불건수,환불수량,DATE
0,출산/육아,분유,국내분유,-,"[매일유업] 리뉴얼 앱솔루트 명작 2FL 분유 1단계, 800g 3개, 0~6개월",5946817178,여성,31~35,1659750.0,25.0,28.0,59700.0,1.0,1.0,2022-07-01
1,출산/육아,분유,국내분유,-,"[매일유업] 리뉴얼 앱솔루트 명작 2FL 분유 1단계, 800g 3개, 0~6개월",5946817178,여성,36~40,1354430.0,21.0,23.0,59700.0,1.0,1.0,2022-07-01
2,출산/육아,분유,국내분유,-,"[리뷰 3,000원][매일유업] 리뉴얼 앱솔루트 명작 2FL 분유 2단계, 800g...",5947218439,여성,31~35,1025400.0,20.0,20.0,0.0,0.0,0.0,2022-07-01
3,출산/육아,분유,국내분유,-,"[매일유업] 리뉴얼 앱솔루트 명작 2FL 분유 1단계, 800g 3개, 0~6개월",5946817178,여성,26~30,946200.0,13.0,16.0,0.0,0.0,0.0,2022-07-01
4,출산/육아,분유,국내분유,-,"[구매확정5,000원+리뷰7,500원][매일유업] 앱솔루트 유기농 궁 분유 2단계 ...",5251125636,여성,31~35,929000.0,7.0,11.0,258000.0,1.0,3.0,2022-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99174,식품,음료,차류,기타차,더그레잇티 콤부차 베리리치 300ml 12개입,6752666034,여성,36~40,0.0,0.0,0.0,12800.0,1.0,1.0,2022-09-02
99175,식품,음료,커피,커피음료,바리스타룰스 무라벨PET 그란데 아메리카노 475ml 20팩,6736685487,남성,41~45,0.0,0.0,0.0,27670.0,1.0,1.0,2022-09-02
99176,출산/육아,분유,국내분유,-,앱솔루트 선천성분유 PKU 1단계 450g 1캔,6120462972,여성,36~40,0.0,0.0,0.0,20000.0,1.0,1.0,2022-09-02
99177,출산/육아,아기간식,유아유제품,-,상하목장 마이리틀 딸기&블루베리 85g x 12팩_냉장,4939051927,여성,31~35,0.0,0.0,0.0,18810.0,2.0,2.0,2022-09-02
99178,출산/육아,아기간식,유아유제품,-,상하목장 마이리틀 사과&바나나 85g x 12팩_냉장,4939057102,여성,31~35,0.0,0.0,0.0,9900.0,1.0,1.0,2022-09-02